# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'ENTRADA'), ('saida', 'SAIDA')], max_length=7)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False, verbose_name='Consistência da frequência!?')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_entrada', models.TimeField(blank=True, null=True)),
                ('h_saida', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=35)),
                ('descricao', models.TextField()),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario')),
                ('freq_inconsistencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Frequencia')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='horarios', to='frequencia.Horarios'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario'),
        ),
    ]
